"""empty message

Revision ID: 2ee5a813cead
Revises: ece042bf584b
Create Date: 2021-04-28 14:53:26.157914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ee5a813cead'
down_revision = 'ece042bf584b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.String(length=60), nullable=True))
    op.add_column('users', sa.Column('number', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('street', sa.String(length=60), nullable=True))
    op.drop_column('users', 'flag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('flag', mysql.VARCHAR(length=30), nullable=True))
    op.drop_column('users', 'street')
    op.drop_column('users', 'number')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###
