"""empty message

Revision ID: 504ad876fc66
Revises: b1f9497c4b20
Create Date: 2021-04-24 18:15:29.026355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '504ad876fc66'
down_revision = 'b1f9497c4b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'date_posted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('date_posted', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
