"""empty message

Revision ID: 70cc3e95dc03
Revises: 1eba2883f5b1
Create Date: 2021-04-23 19:09:14.761250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70cc3e95dc03'
down_revision = '1eba2883f5b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('prices', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'prices')
    # ### end Alembic commands ###
