"""empty message

Revision ID: 878833b9d340
Revises: 262e330d7cb1
Create Date: 2021-04-24 15:10:06.362373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878833b9d340'
down_revision = '262e330d7cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('prices', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'prices')
    # ### end Alembic commands ###
