"""empty message

Revision ID: 92ed35dde180
Revises: 504ad876fc66
Create Date: 2021-04-24 18:15:42.772170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ed35dde180'
down_revision = '504ad876fc66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('date_posted', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'date_posted')
    # ### end Alembic commands ###
