"""empty message

Revision ID: 971384e2a14c
Revises: 9ff69427ddd8
Create Date: 2021-04-24 18:20:54.580466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971384e2a14c'
down_revision = '9ff69427ddd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('date_posted', sa.DateTime(timezone=True), server_default=sa.text('now(NULL)'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'date_posted')
    # ### end Alembic commands ###
