"""empty message

Revision ID: 9ff69427ddd8
Revises: c3c5e818b4a4
Create Date: 2021-04-24 18:20:39.515870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff69427ddd8'
down_revision = 'c3c5e818b4a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('date_posted', sa.DateTime(timezone=True), server_default=sa.text('now(NULL)'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'date_posted')
    # ### end Alembic commands ###
