"""empty message

Revision ID: b1f9497c4b20
Revises: 878833b9d340
Create Date: 2021-04-24 16:00:29.308493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1f9497c4b20'
down_revision = '878833b9d340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('date_posted', sa.DateTime(), nullable=False))
    op.add_column('order', sa.Column('status', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'status')
    op.drop_column('order', 'date_posted')
    # ### end Alembic commands ###
