"""empty message

Revision ID: cac8ebf01779
Revises: c08da877ea78
Create Date: 2021-04-09 09:06:19.320745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cac8ebf01779'
down_revision = 'c08da877ea78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('prices', sa.Float(), nullable=True))
    op.drop_column('products', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('products', 'prices')
    # ### end Alembic commands ###
