"""empty message

Revision ID: fce89fa10022
Revises: cac8ebf01779
Create Date: 2021-04-09 09:09:41.089441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fce89fa10022'
down_revision = 'cac8ebf01779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertoproduct', sa.Column('units', sa.Integer(), nullable=True))
    op.drop_column('usertoproduct', 'unit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertoproduct', sa.Column('unit', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('usertoproduct', 'units')
    # ### end Alembic commands ###
